///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lights
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LightsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("fc513022-b9f9-4d50-9aa6-3fdd280ba705")]
    public partial class LightsRepository : RepoGenBaseFolder
    {
        static LightsRepository instance = new LightsRepository();
        LightsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the LightsRepository element repository.
        /// </summary>
        [RepositoryFolder("fc513022-b9f9-4d50-9aa6-3fdd280ba705")]
        public static LightsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LightsRepository() 
            : base("LightsRepository", "/", null, 0, false, "fc513022-b9f9-4d50-9aa6-3fdd280ba705", ".\\RepositoryImages\\LightsRepositoryfc513022.rximgres")
        {
            _snapxuntitled = new LightsRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fc513022-b9f9-4d50-9aa6-3fdd280ba705")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("0ed5aa1f-39e2-4914-b745-1dcaa5ada8e5")]
        public virtual LightsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class LightsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("0ed5aa1f-39e2-4914-b745-1dcaa5ada8e5")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _switchtosensorInfo;
            RepoItemInfo _switchtoffwInfo;
            RepoItemInfo _ringlightffwInfo;
            RepoItemInfo _surfacelightffwInfo;
            RepoItemInfo _backlightffwInfo;
            RepoItemInfo _ringlightbigInfo;
            RepoItemInfo _surfacelightbigInfo;
            RepoItemInfo _backlightbigInfo;
            RepoItemInfo _boostffwInfo;
            RepoItemInfo _boostbigInfo;
            RepoItemInfo _sliderbacklightInfo;
            RepoItemInfo _slidersurfaceInfo;
            RepoItemInfo _slidersrlInfo;
            RepoItemInfo _textmeasureInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPXUntitled", "/form[@title='SNAP-X - [Untitled]']", parentFolder, 30000, null, true, "0ed5aa1f-39e2-4914-b745-1dcaa5ada8e5", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 30000, null, "8591fe95-4019-4344-bec3-21eb3ae60d5b");
                _switchtosensorInfo = new RepoItemInfo(this, "SwitchToSensor", "container[@controlid='59648']/form/?/?/element[@controlid='59650']/element[@controlid='59648']/toolbar[@controlid='59392']/button[@commandid='40029']", 30000, null, "005e546b-60d9-46c2-88c9-255acfd176dc");
                _switchtoffwInfo = new RepoItemInfo(this, "SwitchToFFW", "container[@controlid='59648']/form//toolbar[@class='ToolbarWindow32' and @instance='6']/button[@commandid='40028']", 30000, null, "67b57a42-ac80-42f3-9ba3-79d82d5a7226");
                _ringlightffwInfo = new RepoItemInfo(this, "RingLightFFW", "container[@controlid='59648']/form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1015']", 30000, null, "c6261fd7-8791-47c1-a487-71fb5738ae9a");
                _surfacelightffwInfo = new RepoItemInfo(this, "SurfaceLightFFW", "container[@controlid='59648']/form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1018']", 30000, null, "e6b91e62-40e4-4547-86b2-2884a48f4bf8");
                _backlightffwInfo = new RepoItemInfo(this, "BackLightFFW", "container[@controlid='59648']/form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1017']", 30000, null, "8c0ef745-275c-4662-b3c7-8b4bde7f908c");
                _ringlightbigInfo = new RepoItemInfo(this, "RingLightBig", "container[@controlid='59648']/form//text[@controlid='1015']", 30000, null, "d6c76fa7-4c91-4372-88f5-a080a74e6469");
                _surfacelightbigInfo = new RepoItemInfo(this, "SurfaceLightBig", "container[@controlid='59648']/form//text[@controlid='1018']", 30000, null, "4198b067-1735-47ea-b45b-e504ce63c6e5");
                _backlightbigInfo = new RepoItemInfo(this, "BackLightBig", "container[@controlid='59648']/form//text[@controlid='1017']", 30000, null, "20e380b2-bda1-4f87-ba2a-7d65c67cbbb5");
                _boostffwInfo = new RepoItemInfo(this, "BoostFFW", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1012']", 30000, null, "3d8c6d69-e681-4c00-8150-c30cfc259dbd");
                _boostbigInfo = new RepoItemInfo(this, "BoostBig", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='1012']", 30000, null, "5b661791-623e-491f-8156-3e217f720489");
                _sliderbacklightInfo = new RepoItemInfo(this, "SliderBackLight", "container[@controlid='59648']/form[@title='Untitled']//slider[@controlid='4117']", 30000, null, "8996d4d5-94c9-482b-a624-f71d0387a8f1");
                _slidersurfaceInfo = new RepoItemInfo(this, "SliderSurface", "container[@controlid='59648']/form[@title='Untitled']//slider[@controlid='4112']", 30000, null, "f7fc55c6-a3f7-48b6-a5b7-78e1097d7fbb");
                _slidersrlInfo = new RepoItemInfo(this, "SliderSRL", "container[@controlid='59648']/form[@title='Untitled']//slider[@controlid='4115']", 30000, null, "802466e2-6818-450c-aaa0-1ead9abbc682");
                _textmeasureInfo = new RepoItemInfo(this, "TextMeasure", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='2394']", 30000, null, "a1e0e14d-3f52-40f8-88a9-afb2dafe071f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ed5aa1f-39e2-4914-b745-1dcaa5ada8e5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ed5aa1f-39e2-4914-b745-1dcaa5ada8e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("8591fe95-4019-4344-bec3-21eb3ae60d5b")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("8591fe95-4019-4344-bec3-21eb3ae60d5b")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The SwitchToSensor item.
            /// </summary>
            [RepositoryItem("005e546b-60d9-46c2-88c9-255acfd176dc")]
            public virtual Ranorex.Button SwitchToSensor
            {
                get
                {
                    return _switchtosensorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToSensor item info.
            /// </summary>
            [RepositoryItemInfo("005e546b-60d9-46c2-88c9-255acfd176dc")]
            public virtual RepoItemInfo SwitchToSensorInfo
            {
                get
                {
                    return _switchtosensorInfo;
                }
            }

            /// <summary>
            /// The SwitchToFFW item.
            /// </summary>
            [RepositoryItem("67b57a42-ac80-42f3-9ba3-79d82d5a7226")]
            public virtual Ranorex.Button SwitchToFFW
            {
                get
                {
                    return _switchtoffwInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToFFW item info.
            /// </summary>
            [RepositoryItemInfo("67b57a42-ac80-42f3-9ba3-79d82d5a7226")]
            public virtual RepoItemInfo SwitchToFFWInfo
            {
                get
                {
                    return _switchtoffwInfo;
                }
            }

            /// <summary>
            /// The RingLightFFW item.
            /// </summary>
            [RepositoryItem("c6261fd7-8791-47c1-a487-71fb5738ae9a")]
            public virtual Ranorex.Text RingLightFFW
            {
                get
                {
                    return _ringlightffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RingLightFFW item info.
            /// </summary>
            [RepositoryItemInfo("c6261fd7-8791-47c1-a487-71fb5738ae9a")]
            public virtual RepoItemInfo RingLightFFWInfo
            {
                get
                {
                    return _ringlightffwInfo;
                }
            }

            /// <summary>
            /// The SurfaceLightFFW item.
            /// </summary>
            [RepositoryItem("e6b91e62-40e4-4547-86b2-2884a48f4bf8")]
            public virtual Ranorex.Text SurfaceLightFFW
            {
                get
                {
                    return _surfacelightffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SurfaceLightFFW item info.
            /// </summary>
            [RepositoryItemInfo("e6b91e62-40e4-4547-86b2-2884a48f4bf8")]
            public virtual RepoItemInfo SurfaceLightFFWInfo
            {
                get
                {
                    return _surfacelightffwInfo;
                }
            }

            /// <summary>
            /// The BackLightFFW item.
            /// </summary>
            [RepositoryItem("8c0ef745-275c-4662-b3c7-8b4bde7f908c")]
            public virtual Ranorex.Text BackLightFFW
            {
                get
                {
                    return _backlightffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BackLightFFW item info.
            /// </summary>
            [RepositoryItemInfo("8c0ef745-275c-4662-b3c7-8b4bde7f908c")]
            public virtual RepoItemInfo BackLightFFWInfo
            {
                get
                {
                    return _backlightffwInfo;
                }
            }

            /// <summary>
            /// The RingLightBig item.
            /// </summary>
            [RepositoryItem("d6c76fa7-4c91-4372-88f5-a080a74e6469")]
            public virtual Ranorex.Text RingLightBig
            {
                get
                {
                    return _ringlightbigInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RingLightBig item info.
            /// </summary>
            [RepositoryItemInfo("d6c76fa7-4c91-4372-88f5-a080a74e6469")]
            public virtual RepoItemInfo RingLightBigInfo
            {
                get
                {
                    return _ringlightbigInfo;
                }
            }

            /// <summary>
            /// The SurfaceLightBig item.
            /// </summary>
            [RepositoryItem("4198b067-1735-47ea-b45b-e504ce63c6e5")]
            public virtual Ranorex.Text SurfaceLightBig
            {
                get
                {
                    return _surfacelightbigInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SurfaceLightBig item info.
            /// </summary>
            [RepositoryItemInfo("4198b067-1735-47ea-b45b-e504ce63c6e5")]
            public virtual RepoItemInfo SurfaceLightBigInfo
            {
                get
                {
                    return _surfacelightbigInfo;
                }
            }

            /// <summary>
            /// The BackLightBig item.
            /// </summary>
            [RepositoryItem("20e380b2-bda1-4f87-ba2a-7d65c67cbbb5")]
            public virtual Ranorex.Text BackLightBig
            {
                get
                {
                    return _backlightbigInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BackLightBig item info.
            /// </summary>
            [RepositoryItemInfo("20e380b2-bda1-4f87-ba2a-7d65c67cbbb5")]
            public virtual RepoItemInfo BackLightBigInfo
            {
                get
                {
                    return _backlightbigInfo;
                }
            }

            /// <summary>
            /// The BoostFFW item.
            /// </summary>
            [RepositoryItem("3d8c6d69-e681-4c00-8150-c30cfc259dbd")]
            public virtual Ranorex.Text BoostFFW
            {
                get
                {
                    return _boostffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BoostFFW item info.
            /// </summary>
            [RepositoryItemInfo("3d8c6d69-e681-4c00-8150-c30cfc259dbd")]
            public virtual RepoItemInfo BoostFFWInfo
            {
                get
                {
                    return _boostffwInfo;
                }
            }

            /// <summary>
            /// The BoostBig item.
            /// </summary>
            [RepositoryItem("5b661791-623e-491f-8156-3e217f720489")]
            public virtual Ranorex.Text BoostBig
            {
                get
                {
                    return _boostbigInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BoostBig item info.
            /// </summary>
            [RepositoryItemInfo("5b661791-623e-491f-8156-3e217f720489")]
            public virtual RepoItemInfo BoostBigInfo
            {
                get
                {
                    return _boostbigInfo;
                }
            }

            /// <summary>
            /// The SliderBackLight item.
            /// </summary>
            [RepositoryItem("8996d4d5-94c9-482b-a624-f71d0387a8f1")]
            public virtual Ranorex.Slider SliderBackLight
            {
                get
                {
                    return _sliderbacklightInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The SliderBackLight item info.
            /// </summary>
            [RepositoryItemInfo("8996d4d5-94c9-482b-a624-f71d0387a8f1")]
            public virtual RepoItemInfo SliderBackLightInfo
            {
                get
                {
                    return _sliderbacklightInfo;
                }
            }

            /// <summary>
            /// The SliderSurface item.
            /// </summary>
            [RepositoryItem("f7fc55c6-a3f7-48b6-a5b7-78e1097d7fbb")]
            public virtual Ranorex.Slider SliderSurface
            {
                get
                {
                    return _slidersurfaceInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The SliderSurface item info.
            /// </summary>
            [RepositoryItemInfo("f7fc55c6-a3f7-48b6-a5b7-78e1097d7fbb")]
            public virtual RepoItemInfo SliderSurfaceInfo
            {
                get
                {
                    return _slidersurfaceInfo;
                }
            }

            /// <summary>
            /// The SliderSRL item.
            /// </summary>
            [RepositoryItem("802466e2-6818-450c-aaa0-1ead9abbc682")]
            public virtual Ranorex.Slider SliderSRL
            {
                get
                {
                    return _slidersrlInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The SliderSRL item info.
            /// </summary>
            [RepositoryItemInfo("802466e2-6818-450c-aaa0-1ead9abbc682")]
            public virtual RepoItemInfo SliderSRLInfo
            {
                get
                {
                    return _slidersrlInfo;
                }
            }

            /// <summary>
            /// The TextMeasure item.
            /// </summary>
            [RepositoryItem("a1e0e14d-3f52-40f8-88a9-afb2dafe071f")]
            public virtual Ranorex.Text TextMeasure
            {
                get
                {
                    return _textmeasureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMeasure item info.
            /// </summary>
            [RepositoryItemInfo("a1e0e14d-3f52-40f8-88a9-afb2dafe071f")]
            public virtual RepoItemInfo TextMeasureInfo
            {
                get
                {
                    return _textmeasureInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}